"""Import the owner's separately supplied pinned source into an empty Afterlight package.

Existing files must have the same bytes. No user checkout, assets or settings
are changed. Git objects avoid platform checkout line-ending transformations.
"""
import argparse
import hashlib
import json
from pathlib import Path
import re
import subprocess

BASELINE = "6367b56e3ff2042199667f2a5bfa50695f4aaf2f"
ROOT = Path(__file__).resolve().parents[1]
RUNTIME = {"src/Garden/Audio.hs", "src/Garden/Input.hs", "src/Garden/Runtime.hs", "src/Garden/Render.hs",
           "src/Garden/Render/GPU.hs", "src/Garden/Render/Radiance.hs", "src/Garden/Render/Resources.hs"}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("original", type=Path)
    args = parser.parse_args()
    original = args.original.resolve()
    git = ["git", "-c", f"safe.directory={original.as_posix()}", "-C", str(original)]
    latest = subprocess.check_output(git + ["rev-parse", "origin/main"], text=True).strip()
    diff = subprocess.check_output(git + ["diff", "--name-only", BASELINE, "origin/main"], text=True).splitlines()
    entries = subprocess.check_output(git + ["ls-tree", "-r", BASELINE], text=True).splitlines()
    modes = {entry.split("\t", 1)[1]: entry.split()[0] for entry in entries}
    names = list(modes)
    selected = [p for p in names if p.startswith(("src/", "assets/shaders/", "tools/", "web/"))
                and not p.startswith("web/guide/")]
    selected += ["LICENSE", "README.md", "garden-of-afterlight.cabal", "cabal.project", "docs/rendering.md"]
    records = []
    oracle = []
    for name in sorted(selected):
        data = subprocess.check_output(git + ["show", f"{BASELINE}:{name}"])
        destination = name
        if name in RUNTIME:
            destination = "runtime/" + name.removeprefix("src/")
        elif name == "README.md":
            destination = "docs/ORIGINAL-README.md"
        elif name in {"garden-of-afterlight.cabal", "cabal.project"}:
            destination = "docs/baseline/" + name
        target = ROOT / destination
        if target.exists() and target.read_bytes() != data:
            raise SystemExit(f"Refusing to overwrite: {target}")
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)
        records.append({"path": destination, "origin": name, "mode": modes[name], "sha256": hashlib.sha256(data).hexdigest(), "bytes": len(data)})
        if name.startswith("src/") and name.endswith(".hs") and name not in {
            "src/Garden/Types.hs", "src/Garden/Audio.hs", "src/Garden/Input.hs", "src/Garden/Runtime.hs", "src/Garden/Render.hs",
            "src/Garden/Render/GPU.hs", "src/Garden/Render/Radiance.hs", "src/Garden/Render/Resources.hs",
        }:
            # Share only the unchanged value types, so World/Cue Eq compares
            # complete values rather than hashes or lossy serialization.
            text = data.decode("utf-8")
            rewritten = re.sub(r"\bGarden\.(?!Types\b)", "Original.Garden.", text).encode("utf-8")
            oracle_path = "test/oracle/Original/" + name.removeprefix("src/")
            oracle_target = ROOT / oracle_path
            if oracle_target.exists() and oracle_target.read_bytes() != rewritten:
                raise SystemExit(f"Refusing to overwrite: {oracle_target}")
            oracle_target.parent.mkdir(parents=True, exist_ok=True)
            oracle_target.write_bytes(rewritten)
            oracle.append({"path": oracle_path, "origin": name, "sha256": hashlib.sha256(rewritten).hexdigest(),
                           "transformation": "Garden.* -> Original.Garden.*, except unchanged Garden.Types"})
    inventory = {
        "schema": 1, "repository": "M-simplifier/garden-of-afterlight", "baseline": BASELINE,
        "latest_origin_main_at_import": latest, "changes_since_previous_baseline": diff,
        "target_base": "839edb6b7a4799ef5e2edd1599729dc7dd14e1a9",
        "files": records, "oracle": oracle,
        "external_assets": {"font": "NotoSansCJKjp-Regular.otf and glyphs.txt absent from original Git",
                            "audio": "Generated by original Garden.Soundscape / Garden.Audio",
                            "shaders": "All six original shaders are included"},
        "excluded": ["editors/", ".agents/", "web/guide/ (documentation, not runtime)"]
    }
    (ROOT / "docs/BASELINE-MANIFEST.json").write_text(json.dumps(inventory, ensure_ascii=False, indent=2) + "\n", encoding="utf-8", newline="\n")
    print(f"Imported {len(records)} original files; {len(oracle)} independent pure oracle modules; latest {latest}; baseline diff {len(diff)}")


if __name__ == "__main__":
    main()
